language: rust
rust: 1.34.2
dist: xenial
sudo: true
cache:
  cargo: true
  timeout: 1024

git:
  depth: 2

env:
  global:
    - RUST_BACKTRACE=full

before_install:
  - cargo sweep --version || cargo install --git https://github.com/holmgr/cargo-sweep --rev 4770deda37a2203c783e301b8c0c895964e8971e
  - cargo sweep -s

script: make ci

before_cache:
  - rm -rf ./target/release
  - rm -rf ./target/debug/incremental/
  - cargo sweep -f

