[package]
name = "ckb-system-scripts"
version = "0.2.0-alpha.1"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"
license = "MIT"
description = "CKB System Scripts"
repository = "https://github.com/nervosnetwork/ckb-system-scripts"
include = ["src/**/*", "Cargo.toml", "build.rs", "specs/cells/*"]

[dependencies]
includedir = "0.5.0"
phf = "0.7.21"

[build-dependencies]
includedir_codegen = "0.5.0"
blake2b-rs = "0.1.4"
faster-hex = "0.3"

[dev-dependencies]
byteorder = "1.3.1"
ckb-core = { git = "https://github.com/nervosnetwork/ckb.git", rev = "f1f838a66b37cd433456d04a5831f7d52db19280" }
ckb-script = { git = "https://github.com/nervosnetwork/ckb.git", rev = "f1f838a66b37cd433456d04a5831f7d52db19280" }
crypto = { git = "https://github.com/nervosnetwork/ckb.git", rev = "f1f838a66b37cd433456d04a5831f7d52db19280" }
dao-utils = { git = "https://github.com/nervosnetwork/ckb.git", rev = "f1f838a66b37cd433456d04a5831f7d52db19280" }
hash = { git = "https://github.com/nervosnetwork/ckb.git", rev = "f1f838a66b37cd433456d04a5831f7d52db19280" }
numext-fixed-hash = "0.1.4"
rand = "0.6.5"
lazy_static = "1.3.0"
