[package]
name = "system-cells"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"
include = ["/specs"]

[dependencies]
includedir = "0.5.0"
phf = "0.7.21"

[build-dependencies]
includedir_codegen = "0.5.0"
blake2b-rs = "0.1.4"
faster-hex = "0.3"
