[[cells]]
name = "multisig"
enable_type_id = true
location = { file = "../../../specs/cells/secp256k1_blake160_multisig_all" }

# reference to on-chain cells, this config is referenced by dep_groups.cells
[[cells]]
name = "seck256k1_data"
enable_type_id = false
location = { tx_hash = "0x549f8043e001717b2e999c5f1238367516f7bd0dc1be502051f639c274ac266d", index = 3 }

# Dep group cells
[[dep_groups]]
name = "multisig_dep_group"
cells = [ "multisig", "seck256k1_data" ]

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x9c26427b733e19f774e74312382946db9548093a"
hash_type = "type"
